# Generated by Django 4.1.7 on 2023-04-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_remove_post_category_post_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="category1", new_name="category",
        ),
    ]
