# Generated by Django 4.1.7 on 2023-05-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_category1_post_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
