# Generated by Django 4.1.7 on 2023-05-02 07:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="body", field=ckeditor.fields.RichTextField(),
        ),
    ]
